# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc.proto for package 'anycable'

require 'grpc'

module AnyCable
  module RPC
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'anycable.RPC'

      rpc :Connect, ConnectionRequest, ConnectionResponse
      rpc :Command, CommandMessage, CommandResponse
      rpc :Disconnect, DisconnectRequest, DisconnectResponse
    end

    Stub = Service.rpc_stub_class
  end
end
