version: "2"
linters:
  enable:
    - decorder
    - errname
    - gocritic
    - gosec
    - grouper
    - misspell
    - staticcheck
    - unconvert
  settings:
    gosec:
      excludes:
        - G115
      severity: medium
      confidence: medium
    govet:
      disable:
        - fieldalignment
      enable-all: true
    staticcheck:
      checks:
        - all
        - -ST1003
        - -ST1005
        - -QF1001
        - -QF1003
        - -S1021
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
