require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rubocop_rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/FileName:
  Exclude:
   - 'lib/anycable-rails.rb'
