FROM debian:stretch-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD .docker/anycable-go-mrb-linux-amd64 /usr/local/bin/anycable-go

USER nobody

ENV ADDR "0.0.0.0:8080"

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/anycable-go"]
