# https://blog.codeship.com/building-minimal-docker-containers-for-go-applications
FROM scratch

ADD .docker/ca-certificates.crt /etc/ssl/certs/
ADD .docker/passwd.nobody /etc/passwd

ADD .docker/anycable-go-linux-amd64 /usr/local/bin/anycable-go

USER nobody

ENV ADDR "0.0.0.0:8080"

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/anycable-go"]
