# Gemfile for running conformance tests with Anyt
source "https://rubygems.org"

gem "nats-pure"

if File.directory?(File.join(__dir__, "../../anycable"))
  $stdout.puts "\n=== Using local gems for Anyt ===\n\n"
  gem "anycable", path: "../../anycable"
  gem "anycable-rails", path: "../../anycable-rails"
  gem "anyt", path: "../../anyt"
  gem "wsdirector-cli", path: "../../wsdirector"
else
  gem "anycable", github: "anycable/anycable"
  gem "anycable-rails", github: "anycable/anycable-rails"
  gem "anyt", github: "anycable/anyt"
  gem "wsdirector-cli", github: "palkan/wsdirector", branch: "v1-dev"
end
