{
 "title": "AnyCable",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_clients_uniq_num" }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_client_msg_total[1m])"
    },
    {
     "expr": "rate(anycable_go_failed_client_msg_total[1m])"
    }
   ]
  },
  {
   "title": "Broadcasts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_broadcast_msg_total[1m])"
    },
    {
     "expr": "rate(anycable_go_failed_broadcast_msg_total[1m])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_failed_auths_total" },
    { "expr": "anycable_go_rpc_error_total" }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_goroutines_num" }
   ]
  }
 ]
}