module AnyCable
  interface _BroadcastAdapter
    def raw_broadcast: (String _data) -> void
    def batching: (?bool enabled) { () -> untyped } -> untyped
    def batching?: () -> (bool | NilClass)
    def broadcast: (String stream, String payload) -> void
    def broadcast_command: (String command, **untyped payload) -> void
    def announce!: () -> void
  end

  module BroadcastAdapters
    class Base
      include _BroadcastAdapter

      private

      def logger: () -> Logger
      def current_batch: () -> Array[untyped]
      def maybe_flush_batch: () -> void
      def batching_enabled_stack: () -> Array[bool]
      def batching_enabled=: (bool) -> void
    end
  end
end
