// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppNode is an autogenerated mock type for the AppNode type
type AppNode struct {
	mock.Mock
}

// HandlePubSub provides a mock function with given fields: msg
func (_m *AppNode) HandlePubSub(msg []byte) {
	_m.Called(msg)
}
