module AnyCable
  class HealthServer
    interface _Runnable
      def running?: () -> bool
    end

    SUCCESS_RESPONSE: [Integer, String]
    FAILURE_RESPONSE: [Integer, String]

    attr_reader server: _Runnable
    attr_reader port: Integer
    attr_reader path: String
    attr_reader http_server: untyped

    def initialize: (_Runnable server, port: Integer port, ?logger: Logger? logger, ?path: String path) -> void
    def start: () -> void
    def stop: () -> void
    def running?: () -> bool

    private

    def logger: () -> Logger
    def build_server: () -> untyped
  end
end
