// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action_cable.proto

package action_cable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_no_type              Type = 0
	Type_welcome              Type = 1
	Type_disconnect           Type = 2
	Type_ping                 Type = 3
	Type_confirm_subscription Type = 4
	Type_reject_subscription  Type = 5
)

var Type_name = map[int32]string{
	0: "no_type",
	1: "welcome",
	2: "disconnect",
	3: "ping",
	4: "confirm_subscription",
	5: "reject_subscription",
}

var Type_value = map[string]int32{
	"no_type":              0,
	"welcome":              1,
	"disconnect":           2,
	"ping":                 3,
	"confirm_subscription": 4,
	"reject_subscription":  5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75ae909d4f019479, []int{0}
}

type Command int32

const (
	Command_unknown_command Command = 0
	Command_subscribe       Command = 1
	Command_unsubscribe     Command = 2
	Command_message         Command = 3
)

var Command_name = map[int32]string{
	0: "unknown_command",
	1: "subscribe",
	2: "unsubscribe",
	3: "message",
}

var Command_value = map[string]int32{
	"unknown_command": 0,
	"subscribe":       1,
	"unsubscribe":     2,
	"message":         3,
}

func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}

func (Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75ae909d4f019479, []int{1}
}

type Message struct {
	Type                 Type     `protobuf:"varint,1,opt,name=type,proto3,enum=action_cable.Type" json:"type,omitempty"`
	Command              Command  `protobuf:"varint,2,opt,name=command,proto3,enum=action_cable.Command" json:"command,omitempty"`
	Identifier           string   `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Message              []byte   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Reconnect            bool     `protobuf:"varint,7,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_75ae909d4f019479, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_no_type
}

func (m *Message) GetCommand() Command {
	if m != nil {
		return m.Command
	}
	return Command_unknown_command
}

func (m *Message) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Message) GetReconnect() bool {
	if m != nil {
		return m.Reconnect
	}
	return false
}

func init() {
	proto.RegisterEnum("action_cable.Type", Type_name, Type_value)
	proto.RegisterEnum("action_cable.Command", Command_name, Command_value)
	proto.RegisterType((*Message)(nil), "action_cable.Message")
}

func init() { proto.RegisterFile("action_cable.proto", fileDescriptor_75ae909d4f019479) }

var fileDescriptor_75ae909d4f019479 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x6e, 0xc2, 0x30,
	0x10, 0x84, 0x31, 0x04, 0x02, 0x0b, 0x05, 0x6b, 0xe9, 0x8f, 0x0f, 0x55, 0x15, 0xf5, 0x50, 0x45,
	0x1c, 0xa8, 0xd4, 0x3e, 0x42, 0x8f, 0x55, 0x2f, 0x51, 0xef, 0x91, 0xe3, 0x2c, 0xc8, 0x2d, 0xb1,
	0x23, 0xc7, 0x08, 0xf1, 0xc2, 0x7d, 0x8e, 0x2a, 0x21, 0x08, 0x72, 0xcb, 0xcc, 0x7c, 0xab, 0xec,
	0xac, 0x01, 0xa5, 0xf2, 0xda, 0x9a, 0x54, 0xc9, 0x6c, 0x47, 0xeb, 0xd2, 0x59, 0x6f, 0x71, 0x76,
	0xed, 0x3d, 0xff, 0x31, 0x08, 0xbf, 0xa8, 0xaa, 0xe4, 0x96, 0xf0, 0x05, 0x02, 0x7f, 0x2c, 0x49,
	0xb0, 0x88, 0xc5, 0xf3, 0x37, 0x5c, 0x77, 0x86, 0xbf, 0x8f, 0x25, 0x25, 0x4d, 0x8e, 0xaf, 0x10,
	0x2a, 0x5b, 0x14, 0xd2, 0xe4, 0xa2, 0xdf, 0xa0, 0x77, 0x5d, 0xf4, 0xe3, 0x14, 0x26, 0x67, 0x0a,
	0x9f, 0x00, 0x74, 0x4e, 0xc6, 0xeb, 0x8d, 0x26, 0x27, 0x06, 0x11, 0x8b, 0x27, 0xc9, 0x95, 0x83,
	0x08, 0x41, 0x2e, 0xbd, 0x14, 0x41, 0x93, 0x34, 0xdf, 0x28, 0x20, 0x2c, 0x4e, 0x7b, 0x89, 0x61,
	0xc4, 0xe2, 0x59, 0x72, 0x96, 0x78, 0x0f, 0x23, 0x47, 0xb2, 0xb2, 0x46, 0x8c, 0x1a, 0xbe, 0x55,
	0xf8, 0x08, 0x13, 0x47, 0xca, 0x1a, 0x43, 0xca, 0x8b, 0x30, 0x62, 0xf1, 0x38, 0xb9, 0x18, 0xab,
	0x02, 0x82, 0xba, 0x02, 0x4e, 0x21, 0x34, 0x36, 0xad, 0x7b, 0xf0, 0x5e, 0x2d, 0x0e, 0xb4, 0x53,
	0xb6, 0x20, 0xce, 0x70, 0x0e, 0x90, 0xeb, 0xaa, 0xe5, 0x79, 0x1f, 0xc7, 0x10, 0x94, 0xda, 0x6c,
	0xf9, 0x00, 0x05, 0xdc, 0x2a, 0x6b, 0x36, 0xda, 0x15, 0x69, 0xb5, 0xcf, 0x2a, 0xe5, 0x74, 0x59,
	0xd7, 0xe5, 0x01, 0x3e, 0xc0, 0xd2, 0xd1, 0x0f, 0x29, 0xdf, 0x0d, 0x86, 0xab, 0x4f, 0x08, 0xdb,
	0x33, 0xe0, 0x12, 0x16, 0x7b, 0xf3, 0x6b, 0xec, 0xc1, 0xa4, 0xed, 0x41, 0x78, 0x0f, 0x6f, 0x60,
	0xd2, 0x4e, 0x64, 0xf5, 0xbf, 0x17, 0x30, 0xdd, 0x9b, 0x8b, 0xd1, 0xaf, 0x37, 0x6b, 0xfb, 0xf2,
	0x41, 0x36, 0x6a, 0x5e, 0xee, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x40, 0xa4, 0x2b, 0x26, 0xcf,
	0x01, 0x00, 0x00,
}
