FROM debian:stretch-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ADD .docker/${TARGETOS}/${TARGETARCH}/anycable-go /usr/local/bin/anycable-go

USER nobody

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/anycable-go"]
