FROM debian:bullseye-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG TARGETPLATFORM=linux/amd64
ADD .docker/${TARGETPLATFORM}/anycable-go /usr/local/bin/anycable-go

USER nobody

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/anycable-go"]
