# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc.proto for package 'anycable'

require "grpc"

module AnyCable
  module GRPC
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "anycable.RPC"

      rpc :Connect, ::AnyCable::ConnectionRequest, ::AnyCable::ConnectionResponse
      rpc :Command, ::AnyCable::CommandMessage, ::AnyCable::CommandResponse
      rpc :Disconnect, ::AnyCable::DisconnectRequest, ::AnyCable::DisconnectResponse
    end

    Stub = Service.rpc_stub_class
  end
end
