module AnyCable
  module WSRPC
    class Client
      %a{rbs:test:skip} def initialize: (
        _App app,
        String url,
        ?id: String,
        ?logger: Logger
      ) -> void

      attr_reader id: String

      def send_message: (untyped msg) -> void
      alias << send_message

      def open: () -> void
      def open?: () -> bool
      def closed?: () -> bool
      def close: () -> void
      def maybe_reconnect: () -> void

      private

      @attempt: Integer
    end
  end
end
