name: Publish AnyCable+ Docker image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_fly:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: "0"
      GOFLAGS: "-mod=vendor"
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Authorize Fly Docker registry
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth docker
      - name: Pull Pro image
        run: |
          docker pull ghcr.io/anycable/anycable-go-pro:edge
      - name: Push Edge Pro image to Fly
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker image tag ghcr.io/anycable/anycable-go-pro:edge registry.fly.io/anycable-saaqs:anycable-go-pro-edge
          docker push registry.fly.io/anycable-saaqs:anycable-go-pro-edge
      - name: Push latest Pro image to Fly
        if: ${{ github.event_name == 'release' }}
        run: |
          docker image tag ghcr.io/anycable/anycable-go-pro:edge registry.fly.io/anycable-saaqs:anycable-go-pro-latest
          docker push registry.fly.io/anycable-saaqs:anycable-go-pro-latest
