name: Upload to Trieve

on:
  push:
    tags:
      - v1.6.*
    branches:
      - main
  workflow_dispatch:

jobs:
  uptrieve:
    uses: anycable/github-actions/.github/workflows/uptrieve.yml@master
    secrets:
      api_key: ${{ secrets.TRIEVE_API_KEY }}
      dataset: ${{ secrets.TRIEVE_DATASET }}
    with:
      latest_version: "v1.6"
